--- # Outline tho Playbook 
- hosts: apacheweb
  user: test
  sudo: yes
  gather_facts: no
  tasks:
   - name: date/time stamp when the playbook starts
     command: /usr/bin/date
     register: timestamp_start
   - debug: var=timestamp_start 
   - name: install apache  web service
     yum: pkg=httpd state=latest
     notify: Start HTTPD
   - name: start the webservice
     service: name=httpd state=restarted
   - name: verify web service is running
     command: systemctl status httpd
     register: result
   - debug: var=result
   - name: install client software
     yum: pkg=telnet state=latest
   - name: install client browser
     yum: pkg=lynx state=latest
   - name: log all installed packages on system
     command: yum list installed
   - debug: var=installed_result
   - name: date/time stamp that playbook ends
     command: /usr/bin/date
   - debug: var=timestamp_end
  handlers:
   - name: Start HTTPD
     service: name=httpd state=restarted
